name: CI for PCRC

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Cache files
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate single file exe using pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller PCRC.spec
        move dist\PCRC.exe package
        pip install -r requirements.txt

    - name: Apply UPX compression
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: |
          package\PCRC.exe
        args: -fq

    - name: Pack PCRC into pyz
      run: |
        move pycraft\minecraft .
        move pycraft\LICENSE .
        rd /s/q pycraft
        md pycraft
        move minecraft pycraft\
        move LICENSE pycraft\

        pip install mcdreforged  # this is required for packing PCRC
        python -m mcdreforged pack -o ./package

    - uses: actions/upload-artifact@v2
      with:
        name: PCRC distributions for ${{ github.sha }}
        path: package
